### ISSUE TITLE
ECONNRESET after indexing

### ISSUE THREAD

**Issue by devpilot-official** [wankdanker/node-redis-index#6]
Hello,

Please, I get this error

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNRESET 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (/Users/devpilot/Desktop/development/sterling/V2_VendorBackend/node_modules/redis-index/node_modules/redis/index.js:341:14)
    at Socket.<anonymous> (/Users/devpilot/Desktop/development/sterling/V2_VendorBackend/node_modules/redis-index/node_modules/redis/index.js:222:14)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379

if I am trying to index a large amount of data

**Comment by wankdanker** [comment]
Are you just using the internal redis client or did you specify your own `obtianClient` and `releaseClient` handlers?

What does you code look like where you are calling `.add()`?

**Comment by devpilot-official** [comment]
Hi @wankdanker thanks for reaching out. I was able to solve the issue, but i think you can help improve this:

so I did
add({
   images: [an array of image links]
});

then I realised I can't assign objects to properties in the .add function
